site_name: SkyU Documentation
repo_name: "skyu.io/skyu-docs"
repo_url: "https://github.com/skyu-io/skyu-documentation"
site_url: "https://docs.skyu.com"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  include_sidebar: true
  language: en
  custom_dir: overrides
  logo: assets/images/skyu.png
  favicon: assets/images/skyu.png
  palette:
    - scheme: skyu
use_directory_urls: false
extra_css: 
  - assets/stylesheets/overrides.css  

nav:
  - Overview: index.md
  - Concepts:
      - concepts/index.md
  - Tutorials:
      - tutorials/index.md
  - API:
      - api/index.md
  - FAQ: 
      - faq/index.md
