site_name: Documentation
repo_name: skyu.io/skyu-docs
repo_url: https://github.com/skyu-io/skyu-docs
site_url: https://docs.skyu.io/
site_description: Internal Developer Platform Built for Developers
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    # - navigation.indexes
    - navigation.sidebar
    - navigation.scrollspy
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - tabs
    # - instant
    - meta

  include_sidebar: true
  language: en
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  palette:
    - scheme: skyu
      primary: blue
      accent: light-blue
      # toggle:
      #   icon: menu
      #   name: Menu

extra_css:
  - assets/stylesheets/overrides.css
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - meta
  # - pymdownx.emoji:
  #     emoji_index: "!!python/name:materialx.emoji.twemoji"
  #     emoji_generator: "!!python/name:materialx.emoji.to_svg"

nav:
  - "Welcome":
      - Overview: "index.md"
      - Getting started: "getting-started.md"
      - Create a Project: "create-project.md"
      - Connect a Kubernetes Cluster: "connect-cluster.md"
      - Deploy your first Application: "deploy-application.md"
  - Concepts:
      - Concepts/resource-heirachy.md
      - Concepts/secret-management.md
      - Concepts/iam.md
      - Concepts/releases.md
      - Concepts/gitops.md
      - Concepts/workflows.md
  - Tutorials:
      - Tutorials/index.md
      - Create Application:
          - Tutorials/applications/source-code-kubernetes-deployment.md
          - Tutorials/applications/docker-compose-jobs-on-ec2.md
          - Tutorials/applications/web-application-on-aws-cloudfront.md
          - Tutorials/applications/nodejs-to-lambda.md
      - Create Image Registry:
          - Tutorials/image-registry/docker-registry.md
          - Tutorials/image-registry/amazon-ecr.md
      - Manage Users:
          - Tutorials/user-management/iam.md
      - Create Infrastructure:
          - Tutorials/infrastructure/enable-infrastructure-feature.md
          - Tutorials/infrastructure/deploy-rds-instance-aws.md
  - API:
      - API/index.md
  - FAQ:
      - FAQ/index.md
