site_name: SkyU Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: black S
  custom_dir: overrides
  logo: assets/images/skyu-logo-512.png
  favicon: assets/images/favicon.ico

nav:
  - Overview:
      - index.md
      - Getting started: getting-started.md
      - CLI: cli.md
      - Support: support.md
  - Concepts: 
      - Concepts/index.md
  - Tutorials:
      - Tutorials/index.md
  - API: 
      - API/index.md
  - FAQ: 
      - FAQ/index.md


   
